name: apnea-detection
channels:
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pytest
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - jupyter
  - scipy
  - conda-forge::einops
  - numba
  - scikit-learn
  - seaborn
  - pip:
    - wfdb

# --> Install PyTorch into existing environment using the following command:
#     conda install -y pytorch cudatoolkit=11.1 -c pytorch -c nvidia
